import { z } from 'zod';

export const IndependentWorkContractScalarFieldEnumSchema = z.enum([
  'id',
  'type',
  'admissionDate',
  'address',
  'studyLevel',
  'studyDescription',
  'email',
  'emergencyObservation',
  'startContractDate',
  'endContractDate',
  'amountWithoutDiscounts',
  'amountWithDiscounts',
  'decreeNumber',
  'accountCodeReference',
  'monthlyBonusAmount',
  'bonusMonths',
  'laborObservations',
  'observations',
  'directorateCodeReference',
  'status',
  'approvalEmployeeId',
  'approvalDirectorateCodeReference',
  'informantEmployeeId',
  'informantDirectorateCodeReference',
  'departmentId',
  'employeeRoleId',
  'employeeLaborId',
  'cityId',
  'templateContractId',
  'workContractId',
  'enabled',
  'archived',
  'createdAt',
  'updatedAt',
]);

export default IndependentWorkContractScalarFieldEnumSchema;
